name: Action
author: AliuQ
description: Action for aliuq/apps-image repository
inputs:
  action:
    description: 'Action to perform, e.g. check-version, resolve-meta'
    required: true
  token:
    description: Personal Access Token (PAT) for the repository
    required: true
  app:
    description: 'App name, e.g. tgcf'
    required: false
  create_pr:
    description: Create a PR if the version is outdated
    required: false
    default: 'true'
  debug:
    description: Debug mode
    required: false
  context:
    description: 'Context directory, only works on resolve-meta, e.g. apps/tgcf'
    required: false

# outputs:

runs:
  using: node20
  main: dist/index.js

branding:
  icon: message-square
  color: blue
