name: Build and Distribute Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - 'app/**'
      - 'base/**'
      - 'test/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed names and outout
        id: get_changed_names
        shell: bash
        run: |
          diff=$(git diff --name-only HEAD^)
          if [ -z "$diff" ]; then
            echo "No changes in app or base directory"
            exit 0
          fi

          changed_names=$(echo "$diff" | grep -E '^(app|base|test)/' | sort | uniq)
          if [ -z "$changed_names" ]; then
            echo "No changes in app or base directory"
            exit 0
          fi
          echo "changed_names=$(echo $changed_names)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          if [ -z "${{ steps.get_changed_names.outputs.changed_names }}" ]; then
            echo "No changes in app or base directory"
            exit 0
          fi

          tree .

          for name in ${{ steps.get_changed_names.outputs.changed_names }}; do
            IFS='/' read -ra ADDR <<< "$name"
            category=${ADDR[0]}
            imageName=${ADDR[1]}
            dockerfileName=${ADDR[2]}

            if [[ $dockerfileName != "Dockerfile" && $dockerfileName != "Dockerfile."* ]]; then
              echo "No Dockerfile found in $name"
              continue
            fi

            tag=$(git log -1 --pretty=format:%h -- $name)
            if [[ $dockerfileName == "Dockerfile."* ]]; then
              tag=${dockerfileName:11}
            fi

            builderName="builder-$imageName-$tag"

            echo ""
            echo "文件路径: $name"
            echo "镜像分类: $category"
            echo "镜像名称: $imageName"
            echo "镜像标签: $tag"
            echo "Dockerfile 文件名: $dockerfileName"
            echo "是否自定义标签: $customTag"
            echo "执行命令 ($builderName):"

            echo "docker buildx create --name $builderName --driver docker-container"
            docker buildx create --name $builderName --driver docker-container

            echo "docker buildx use $builderName"
            docker buildx use $builderName
            if [ $category == "base" ]; then
              echo "docker buildx build --no-cache -t $imageName:$tag --load --label "maintainer=AliuQ<aliuq@bilishare.com>" --label "category=$category" -f $name ./$category/$imageName/"
              docker buildx build --no-cache -t $imageName:$tag --load --label "maintainer=AliuQ<aliuq@bilishare.com>" --label "category=$category" -f $name ./$category/$imageName/
            else
              echo "docker buildx build --no-cache -t $imageName:$tag --load --label "category=$category" -f $name ./$category/$imageName/"
              docker buildx build --no-cache -t $imageName:$tag --load --label "category=$category" -f $name ./$category/$imageName/
            fi
          done

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: |
          for name in ${{ steps.get_changed_names.outputs.changed_names }}; do
            IFS='/' read -ra ADDR <<< "$name"
            category=${ADDR[0]}
            imageName=${ADDR[1]}
            dockerfileName=${ADDR[2]}

            tag=$(git log -1 --pretty=format:%h -- $name)
            customTag=false
            if [[ $dockerfileName == "Dockerfile."* ]]; then
              customTag=true
              tag=${dockerfileName:11}
            fi

            dockerHubName="${{ secrets.DOCKERHUB_USERNAME }}/$imageName:$tag"
            docker tag $imageName:$tag $dockerHubName
            echo "docker push $dockerHubName"

            if [ $customTag == false ]; then
              dockerHubLatestName="${{ secrets.DOCKERHUB_USERNAME }}/$imageName:latest"
              docker tag $imageName:$tag $dockerHubLatestName
              echo "docker push $dockerHubLatestName"
            fi

            echo $(docker images)
          done

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Tag Docker image for GitHub Container Registry
      #   run: docker tag myapp:latest ghcr.io/${{ github.repository_owner }}/myapp:latest

      # - name: Push to GitHub Container Registry
      #   run: docker push ghcr.io/${{ github.repository_owner }}/myapp:latest
