name: Build and Distribute Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - 'app/**'
      - 'base/**'
      - 'test/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed names and outout
        id: get_changed_names
        shell: bash
        run: |
          changed_names=$(git diff --name-only HEAD^ | grep -E '^(app|base|test)/' | sort | uniq)
          echo "changed_names=$(echo $changed_names)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          if [ -z "${{ steps.get_changed_names.outputs.changed_names }}" ]; then
            echo "No changes in app or base directory"
            exit 0
          fi

          for name in ${{ steps.get_changed_names.outputs.changed_names }}; do
            IFS='/' read -ra ADDR <<< "$name"
            category=${ADDR[0]}
            imageName=${ADDR[1]}
            dockerfileName=${ADDR[2]}

            if [[ $dockerfileName != "Dockerfile" && $dockerfileName != "Dockerfile."* ]]; then
              echo "No Dockerfile found in $name"
              continue
            fi

            tag=$(git log -1 --pretty=format:%h -- $name)
            customTag=false
            if [[ $dockerfileName == "Dockerfile."* ]]; then
              customTag=true
              tag=${dockerfileName:11}
            fi

            builderName="builder-$imageName-$tag"

            echo ""
            echo "文件路径: $name"
            echo "镜像分类: $category"
            echo "镜像名称: $imageName"
            echo "镜像标签: $tag"
            echo "Dockerfile 文件名: $dockerfileName"
            echo "是否自定义标签: $customTag"
            echo "执行命令（$builderName）:"
            echo "  docker buildx create --name $builderName --driver docker-container"
            echo "  docker buildx use $builderName"
            echo "  docker buildx build --no-cache -t $imageName:$tag -f $dockerfileName --push ./$category/$imageName/"
          done


      # - name: Build Docker image
      #   run: docker build -t myapp:latest .

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push to Docker Hub
      #   run: docker push myapp:latest

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Tag Docker image for GitHub Container Registry
      #   run: docker tag myapp:latest ghcr.io/${{ github.repository_owner }}/myapp:latest

      # - name: Push to GitHub Container Registry
      #   run: docker push ghcr.io/${{ github.repository_owner }}/myapp:latest
