name: Check Version

on:
  workflow_dispatch:
    inputs:
      app:
        description: App name, e.g. weektodo
        required: false
        type: string
      create_pr:
        description: Create a PR if the version is outdated
        required: false
        type: boolean
        default: false
      debug:
        description: Debug mode
        required: false
        type: boolean
        default: false
  push:
    branches:
      - master
    paths:
      - apps/*/meta.json

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && contains(github.event.head_commit.message, 'force build'))
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Version
        uses: ./action
        with:
          action: check-version
          token: ${{ secrets.PAT }}
          app: ${{ inputs.app }}
          create_pr: ${{ inputs.create_pr }}
          debug: ${{ inputs.debug }}
