name: Check version on test mode

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug mode'
        required: false
        default: false
        type: boolean

jobs:
  check-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check version
        uses: ./check-version-action
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          debug: ${{ inputs.debug }}
