name: Check version
run-name: ${{ inputs.app !== '' && format("Check {0} Version", inputs.app) || 'Check All Apps Version' }}

on:
  workflow_dispatch:
    inputs:
      app:
        description: App name, e.g. tgcf
        required: false
        type: string
      context:
        description: 'Context directory, e.g. apps/tgcf'
        required: false
        type: string
      create_pr:
        description: Create a PR if the version is outdated
        required: false
        type: boolean
        default: false

jobs:
  check-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check version
        uses: ./action
        with:
          action: check-version
          token: ${{ secrets.PAT }}
          app: ${{ inputs.app }}
          context: ${{ inputs.context }}
          create_pr: ${{ inputs.create_pr }}
