name: Check Version

on:
  schedule:
    - cron: '0 */6 * * *' # 每 6 小时检查一次
  workflow_dispatch:
    inputs:
      context:
        description: 上下文目录，例如 apps/icones
        type: choice
        default: all
        options:
          - all
          # ContextStart
          - apps/cobalt
          - apps/icones
          - apps/inpaint-web
          - apps/jsonhero-web
          - apps/lsky
          - apps/memogram
          - apps/readest
          - apps/srcbook
          - apps/telegram-upload
          - apps/telemirror
          - apps/weektodo
          - apps/yulegeyu
          - base/alpine
          - base/nginx
          - base/self
          - base/tg-session
          - test/icones
          - test/self
          - test/weektodo
          - test/weektodo-mul
          # ContextEnd
      create_pr:
        description: 是否创建 PR
        type: choice
        default: 'false'
        options:
          - 'true'
          - 'false'
          - development
      debug:
        description: Debug 模式
        type: boolean
        default: false
  push:
    branches:
      - master
    paths:
      - apps/*/meta.json
      - apps/*/Dockerfile
      - apps/*/Dockerfile.*
      - base/*/meta.json
      - base/*/Dockerfile
      - base/*/Dockerfile.*
      - test/*/meta.json
      - test/*/Dockerfile
      - test/*/Dockerfile.*

jobs:
  check-version:
    name: Check Version
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || (github.event_name == 'push' && github.event.head_commit && !contains(github.event.head_commit.message, '[skip check]'))
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 0 = 完整历史

      - name: Check Version
        uses: ./action/check-version
        env:
          TZ: Asia/Shanghai
        with:
          token: ${{ secrets.PAT }}
          context: ${{ inputs.context }}
          create_pr: ${{ inputs.create_pr }}
          debug: ${{ inputs.debug }}
