name: Check Version

on:
  schedule:
    - cron: '0 */6 * * *' # 每 6 小时检查一次
  workflow_dispatch:
    inputs:
      create_pr:
        description: 有新版本时创建 PR
        type: boolean
        default: false
      debug:
        description: Debug 模式
        type: boolean
        default: false
      mock:
        description: 有新版本时创建 PR，但不会触发镜像构建
        type: boolean
        default: false
      context:
        description: 上下文目录，例如 apps/icones
        type: choice
        default: all
        options:
          - all
          - apps/cobalt
          - apps/icones
          - apps/inpaint-web
          - apps/jsonhero-web
          - apps/lsky
          - apps/memogram
          - apps/readest
          - apps/srcbook
          - apps/telegram-upload
          - apps/telemirror
          - apps/tgcf
          - apps/weektodo
          - apps/yulegeyu
  push:
    branches:
      - master
    paths:
      - apps/*/meta.json

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'schedule') ||
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && contains(github.event.head_commit.message, 'force check'))
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Version
        uses: ./action
        with:
          action: check-version
          token: ${{ secrets.PAT }}
          context: ${{ inputs.context }}
          create_pr: ${{ inputs.create_pr }}
          debug: ${{ inputs.debug }}
          mock: ${{ inputs.mock }}
