name: Check Version

on:
  # schedule:
  #   - cron: '0 */6 * * *' # 每 6 小时检查一次
  workflow_dispatch:
    inputs:
      context:
        description: 上下文目录，例如 apps/icones
        type: choice
        default: all
        options:
          - all
          - apps/cobalt
          - apps/icones
          - apps/inpaint-web
          - apps/jsonhero-web
          - apps/lsky
          - apps/memogram
          - apps/readest
          - apps/srcbook
          - apps/telegram-upload
          - apps/telemirror
          - apps/tgcf
          - apps/weektodo
          - apps/yulegeyu
          - test/weektodo
      enable_pr:
        description: 是否创建 PR
        type: choice
        default: "true"
        options:
          - "true"
          - "false"
          - "development"
      concurrency:
        description: 并发数，控制同时处理的应用数量
        type: number
        default: 3
      debug:
        description: Debug 模式
        type: boolean
        default: false
      log_format:
        description: 日志格式
        type: choice
        default: detailed
        options:
          - simple
          - detailed
          - json
  push:
    branches:
      - master
      - dev
    paths:
      - test/*/meta.json
      - test/*/Dockerfile
      - test/*/Dockerfile.*

jobs:
  check-version:
    runs-on: ubuntu-latest
    # if: |
    #   (github.event_name == 'schedule') ||
    #   (github.event_name == 'workflow_dispatch') ||
    #   (github.event_name == 'push' && contains(github.event.head_commit.message, 'force check'))
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Version
        uses: ./action/check-version
        env:
          TZ: Asia/Shanghai
        with:
          token: ${{ secrets.PAT }}
          context: ${{ inputs.context }}
          enable_pr: ${{ inputs.enable_pr }}
          debug: ${{ inputs.debug }}
          concurrency: ${{ inputs.concurrency }}
          log_format: ${{ inputs.log_format }}
