name: Check version on test mode

on:
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check version
        uses: ./check-version-action
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
