name: Check version on test mode

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug mode'
        required: false
        default: false
        type: boolean
      app:
        description: 'App name'
        required: false
        type: string

jobs:
  check-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check version
        uses: ./check-version-action
        with:
          myToken: ${{ secrets.PAT }}
          debug: ${{ inputs.debug }}
          app: ${{ inputs.app }}
